import type { Guest } from './types';

export const SEED_GUESTS: Guest[] = [
  {
    id: 'guest-chen-david',
    name: 'Mr. David Chen',
    room: '412',
    booking_dates: { check_in: '2026-05-14', check_out: '2026-05-18' },
    vip_tier: 'platinum',
    preferences: [
      'Room temperature set cool (~67°F)',
      'Extra pillows',
      'Sparkling water on arrival',
    ],
    learnedPreferences: [],
    past_stays: 8,
    notes: 'Severe nut allergy — confirmed by F&B on every visit. Tech executive, often takes early-morning calls.',
    linkedInSummary: 'VP of Product at Horizon Labs (Series C AI infrastructure startup). Previously led product at Stripe and Google. Stanford CS grad, active angel investor.',
    recentNews: [
      'Keynote speaker at TechCrunch Disrupt SF last month',
      'Horizon Labs recently closed $80M Series C, coverage in TechCrunch and Forbes',
      'Published op-ed in Wired on responsible AI deployment',
    ],
    interests: ['Cold brew coffee', 'Jazz', 'Road cycling', 'Coldplay'],
    dietaryRestrictions: ['Severe nut allergy (anaphylactic)', 'No pork'],
    preferredLanguage: 'English',
    lifetimeValue: '$42,000',
    interaction_log: [],
  },
  {
    id: 'guest-marchetti-sofia',
    name: 'Ms. Sofia Marchetti',
    room: '808',
    booking_dates: { check_in: '2026-05-12', check_out: '2026-05-20' },
    vip_tier: 'legacy',
    preferences: [
      'Fresh flowers replaced daily (prefers peonies or white roses)',
      'Italian-language newspapers each morning',
      'Espresso service before 7am',
    ],
    learnedPreferences: [],
    past_stays: 22,
    notes: 'Italian luxury fashion buyer, Milan-based. Travels seasonally for fashion weeks. Knows GM personally.',
    linkedInSummary: 'Senior Buying Director at Rinascente Group. 20+ years in luxury retail. Adjunct lecturer at Istituto Marangoni. Influential voice in sustainable luxury.',
    recentNews: [
      'Featured in Vogue Italia\'s "Gatekeepers of Italian Fashion" profile',
      'Led Rinascente\'s new sustainable sourcing initiative launched in April',
      'Panelist at Milan Fashion Week sustainability forum',
    ],
    interests: ['Opera', 'Baroque art', 'Sicilian cuisine', 'Vintage Hermès', 'Contemporary Italian ceramics'],
    dietaryRestrictions: ['Lactose intolerant', 'Prefers organic produce'],
    preferredLanguage: 'Italian (English spoken fluently)',
    lifetimeValue: '$128,000',
    interaction_log: [],
  },
  {
    id: 'guest-patel-raj',
    name: 'Dr. Raj Patel',
    room: '215',
    booking_dates: { check_in: '2026-05-15', check_out: '2026-05-17' },
    vip_tier: 'gold',
    preferences: [
      'Kosher meals (certified)',
      'Quiet room away from elevators',
      'Late checkout when possible',
    ],
    learnedPreferences: [],
    past_stays: 0,
    notes: 'First stay. In town for the International Cardiology Conference. Speaking on day 2.',
    linkedInSummary: 'Interventional Cardiologist and Associate Professor at Johns Hopkins Medicine. Researcher in minimally invasive cardiac procedures. 80+ peer-reviewed publications.',
    recentNews: [
      'Published landmark study in NEJM on transcatheter valve replacement outcomes',
      'Appointed to AHA Scientific Advisory Board this spring',
      'TED-Med talk on AI-assisted cardiac diagnostics has 2.1M views',
    ],
    interests: ['Classical tabla', 'Cricket', 'Philosophy of medicine', 'Science communication'],
    dietaryRestrictions: ['Strictly kosher', 'Vegetarian', 'No shellfish'],
    preferredLanguage: 'English',
    lifetimeValue: '$3,200',
    interaction_log: [],
  },
  {
    id: 'guest-whitfield-eleanor',
    name: 'Mrs. Eleanor Whitfield',
    room: '1102',
    booking_dates: { check_in: '2026-05-10', check_out: '2026-05-24' },
    vip_tier: 'legacy',
    preferences: [
      'Afternoon tea served in suite at 4:00pm sharp',
      'Earl Grey, milk on the side, two scones with clotted cream',
      'Housekeeping only between 10am–noon',
    ],
    learnedPreferences: [],
    past_stays: 43,
    notes: 'Retired philanthropist, long-time patron. Prefers to be addressed formally. Mobility-aware staff escort appreciated.',
    linkedInSummary: 'Retired Chair of the Whitfield Foundation, which has donated $200M to arts, education, and heritage preservation. Former trustee of the Tate Modern and National Trust.',
    recentNews: [
      'Whitfield Foundation announced £5M grant to restore Elizabethan theatre in Bath',
      'Named honorary Fellow of the Royal Academy of Arts',
      'Subject of a BBC Radio 4 documentary on postwar British philanthropy',
    ],
    interests: ['British garden design', 'Watercolour painting', 'Agatha Christie', 'Choral evensong', 'Orchid cultivation'],
    dietaryRestrictions: ['Gluten-free preferred', 'No red meat', 'Decaf only after 3pm'],
    preferredLanguage: 'English',
    lifetimeValue: '$380,000',
    interaction_log: [],
  },
];
